### ISSUE TITLE
Prompt for storage permissions on Marshmallow

### ISSUE THREAD

**Issue by dgw** [Piranhaplant/LLP2ST#1]
It's not a huge deal, because the app (unlike others I've tried) doesn't crash when it can't access the external storage—but it would be nice if users didn't have to go into the app's settings and manually grant it Storage permissions.

See https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-runtime-permissions

**Comment by Piranhaplant** [comment]
Thanks for letting me know about this. I don't have an Android 6.0 device yet, so I hadn't tested it. I have fixed the issue and I'll put out a release soon with this and some other bug fixes.

**Comment by dgw** [comment]
3d16926 is what should close this, for future reference.

Thanks, @Piranhaplant. I'll specifically test this when I update, both denying and allowing the permission at runtime.

**Comment by dgw** [comment]
Handles nicely under both cases (Allow/Deny access). :+1:

**Comment by Piranhaplant** [comment]
Great, thanks for testing this for me!
