### ISSUE TITLE
Error downloading

### ISSUE THREAD

**Issue by Pokeranger** [Piranhaplant/LLP2ST#4]
Just started the other day, but I can't download any new songs, just prompts "Error downloading song: Internal error"
![image](https://user-images.githubusercontent.com/37203123/37191324-6d3a64f4-2324-11e8-8aad-9fabddbdba73.png)

**Comment by Piranhaplant** [comment]
Thank you for the report. LLPractice had updated to send song data in a new format that the app didn't know how to handle. I have uploaded a new release (1.2.4) that works with the new format.

Let me know if you are still encountering issues with the new version.
